import 'dart:async';

import 'package:flame_audio/flame_audio.dart';

/// Sound effects used by the game.
///
/// The WAV files are generated by `tool/generate_endless_breakout_sfx.dart`.
enum BreakoutSound {
  /// Ball hits the paddle.
  paddle('paddle.wav'),

  /// Ball damages a hard brick without breaking it.
  brickHit('brick_hit.wav'),

  /// A brick breaks.
  brickBreak('brick_break.wav'),

  /// An explosive brick goes off.
  explosion('explosion.wav'),

  /// An item capsule is caught.
  item('item.wav'),

  /// Laser volley fired.
  laser('laser.wav'),

  /// Level increased.
  levelUp('level_up.wav'),

  /// A life is lost.
  lifeLost('life_lost.wav'),

  /// Game over.
  gameOver('game_over.wav');

  new(this.fileName);

  /// File name under `assets/audio/endless_breakout/`.
  final String fileName;
}

/// Plays sound effects for the game.
abstract interface class BreakoutAudio {
  /// Loads every sound. Must complete before [play] is called.
  Future<void> load();

  /// Plays [sound] once.
  void play(BreakoutSound sound);

  /// Releases audio resources.
  Future<void> dispose();
}

/// [BreakoutAudio] backed by `flame_audio` pools.
class FlameBreakoutAudio implements BreakoutAudio {
  static const _directory = 'endless_breakout';
  static const _volume = 0.6;

  final Map<BreakoutSound, AudioPool> _pools = {};

  @override
  Future<void> load() async {
    for (final sound in BreakoutSound.values) {
      _pools[sound] = await FlameAudio.createPool(
        '$_directory/${sound.fileName}',
        maxPlayers: 4,
      );
    }
  }

  @override
  void play(BreakoutSound sound) {
    final pool = _pools[sound];
    if (pool == null) {
      throw StateError('Sound $sound was played before load() completed');
    }
    unawaited(pool.start(volume: _volume));
  }

  @override
  Future<void> dispose() async {
    for (final pool in _pools.values) {
      await pool.dispose();
    }
    _pools.clear();
  }
}
